language: ruby

rvm:
  - 1.9.3
  - ruby-head
  - rbx-2.2.7

sudo: false

env:
  - ESCAPE_UTILS=1
  - ""

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: rbx-2.2.7
      env: ESCAPE_UTILS=1
