language: ruby

rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode

sudo: false

env:
  - ESCAPE_UTILS=1
  - ""

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: jruby-19mode
      env: ESCAPE_UTILS=1
