sudo: required
language: ruby
branches:
  only:
    - master
services:
  - docker
env:
  - DOCKER_CONTAINER=test-container
before_script:
  - docker build -t test-image .
  - docker run -d --name $DOCKER_CONTAINER test-image
script:
  - bundle exec rspec
