language: ruby
cache: bundler
dist: trusty
sudo: false

rvm:
  - 1.9.3
  - ruby-head
  - rbx-2
  - rbx-3

env:
  - ESCAPE_UTILS=1
  - ""

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: rbx-3
  exclude:
    - rvm: rbx-2
      env: ESCAPE_UTILS=1
