language: ruby

rvm:
  - 1.9.3
  - ruby-head
  - rbx
  - rbx-3

sudo: false

env:
  - ESCAPE_UTILS=1
  - ""

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: rbx-3
  exclude:
    - rvm: rbx
      env: ESCAPE_UTILS=1
    - rvm: rbx-3
      env: ESCAPE_UTILS=1
