sudo: required
language: ruby
branches:
  only:
    - master
services:
  - docker
env:
  - TARGET_CONTAINER_ID=test-container
before_script:
  - docker build -t test-image .
  - docker run -d --name $TARGET_CONTAINER_ID test-image
script:
  - bundle exec rspec
