apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: k0kubun/worker:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_HOST
          value: mysql.default.svc.cluster.local
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_PASSWORD
          valueFrom:
            # Not recommended to write password on command line, but you can use:
            # kubectl create secret generic mysql-secret --from-literal=password='raw-password'
            secretKeyRef:
              name: mysql-secret
              key: password
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
