---
shallow_clone: true
platform:
  - x64
environment:
  ruby_version: "24-%Platform%"
  zlib_version: "1.2.11"
  matrix:
    - vs: "120"
test_script:
  - ruby -e "puts 'hello world'"
notifications:
  - provider: Slack
    incoming_webhook:
      secure: WHfGy/gGheFHswUm9HsjNj3zDfbFX7UIGentpC1Z8eGcki1X0ow5ajdghoPBLjYyaTCoUiPXIiLNKYGKrClPJCemGdQfsCu0tldrZzSX+UQ=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
