# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: job1
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - checkout: none
  - script: |
      sleep 1
      dir
      if %errorlevel% == 0 (exit 0)
      dir /0
      if %errorlevel% == 0 (echo ok) else (echo error)
    continueOnError: true
  - script: |
      for /l %%i in (1,1,5) do (
        set errorlevel=
        dir /0
        if %errorlevel% == 0 (echo ok) else (echo error)
      )
#  - script: |
#      for /l %%i in (1,1,5) do (
#        echo hello
#        echo %errorlevel%
#        echo %errorlevel%
#        if %errorlevel% == 0 (exit 0) else (
#          if %%i == 5 (exit 1) else (
#            echo yo
#            sleep 2
#          )
#        )
#      )
#  - script: |
#      for /l %%i in (1,1,5) do (
#        aaaaaaaaaa
#        echo %errorlevel%
#        echo %errorlevel%
#        if %errorlevel% == 0 (exit 0) else (
#          if %%i == 5 (exit 1) else (
#            echo yo
#            sleep 2
#          )
#        )
#      )
