# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: job1
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - checkout: none
  - script: |
      for /l %%i in (1,1,5) do (
        dir aaa
        if not %errorlevel% == 0 (
          if i == 5 (exit 1) else (sleep 1)
        )
      )
