# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: job1
  displayName: fixed
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: echo job1

- job: job2
  displayName: fixed
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: echo job2

- job: job3
  displayName: fixed
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: echo job3
