name: notify-slack
description: You can notify slack of GitHub Actions.
author: k0kubun
inputs:
  type:
    description: success or failure
  text:
    description: You can overwrite text
runs:
  using: docker
  image: 'docker://ruby:2.6-slim'
  args:
    - /usr/local/bin/ruby
    - -e
    - |-
      puts "hello world"
