name: notify-slack
description: Notify Slack for GitHub Actions
author: k0kubun
inputs:
  status:
    description: Success or Failure
  matrix_name:
    description: Matrix task name
  committer_name:
    description: Git committer name
  commit_message:
    description: Git commit message
  commit_timestamp:
    description: Git commit timestamp
runs:
  using: node12
  main: lib/main.js
