name: notify-slack
description: You can notify slack of GitHub Actions.
author: k0kubun
inputs:
  status:
    description: Success or Failure
  test_task:
    description: Matrix test_task
runs:
  using: docker
  image: 'docker://ruby:2.6-slim'
  args:
    - /usr/local/bin/ruby
    - -e
    - |-
      #payload = ENV.slice(
      #  'GITHUB_SHA',
      #  ''
      #)
      puts "hello world"
      p ARGV
      system('pwd')
      system('ls -la')
      require 'pp'
      pp ENV

      #"GITHUB_SHA"=>"65fd37d7956d916cd3417bb770adc3b9b4cc94a7",
      #"GITHUB_WORKFLOW"=>"ubuntu",
      #"GITHUB_BASE_REF"=>"",
      #"GITHUB_EVENT_NAME"=>"push",
      #"GITHUB_ACTOR"=>"k0kubun",
      #"SLACK_WEBHOOK_URL"=>"***",
      #"GITHUB_REF"=>"refs/heads/master",
      #"GITHUB_REPOSITORY"=>"k0kubun/misc",
      #"GITHUB_EVENT_PATH"=>"/github/workflow/event.json",
      #"RUNNER_WORKSPACE"=>"/home/runner/work/misc",
      #"INPUT_TYPE"=>"success",
      #"GITHUB_HEAD_REF"=>"",
      #"GITHUB_WORKSPACE"=>"/github/workspace",
      #"GITHUB_ACTION"=>"self",
