name: ubuntu
on: [push]
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        run: |
          pwd
          find .
      - uses: ./.github/actions/notify-slack
        with:
          type: success
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()
