name: ubuntu
on: [push]
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: |
          git clone --depth=1 https://github.com/k0kubun/misc .
      - name: test
        run: |
          pwd
          find .
      - uses: ./.github/actions/notify-slack
        with:
          type: success
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()
