name: ubuntu
on: [push]
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: |
          git clone --depth=1 https://github.com/k0kubun/misc .
      - name: test
        run: exit 1
      - name: Debug github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: ./.github/actions/notify-slack
        with:
          type: success
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()
  notify:
    runs-on: ubuntu-latest
    needs: latest
    steps:
      - name: hello
        run: echo hello
