name: ubuntu
on: [push]
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo hello
      - uses: 8398a7/action-slack@v1
        with:
          type: success
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()
